Add external requests handling for ratsd core
veraison/ratsd pull request #17
Opened 2024-12-23 19:50 UTC by cowbon

Add the definition for endpoint `/ratsd/chares` based on the OpenAPI YAML from Thomas F. Support for Authentication tokens and test suites will be added in later patches

2025-01-08 20:43 UTC, jraman567 requested changes

2025-01-08 20:43 UTC, jraman567 commented on cmd/main.go
> +		Protocol: "https",
Thanks for the PR, Tom. I'd like to share my thoughts on generating the API code using `oapi-codegen`.

- tools/tools.go isn't necessary since you're referring to the GitHub repo directly. So please remove the tools directory.
- I'm unsure if committing api.gen.go directly is a good idea. Since you have api/docs.go, we can run `go generate` within the api directory at some point during the build process to generate this file. That would keep the source code up to the spec in ratsd.yaml
- Since the code is auto-generated, it should be good. However, should we add functional tests for it?

Also, we need to do the following in general for the repo:

- Add a CI pipeline that runs whenever someone submits a PR
- For every commit in your PR, please run `go mod tidy` individually and ensure the mod file is up-to-date.

I still need to review the third commit. I'll wrap it up by tonight.

2025-01-09 18:35 UTC, jraman567 requested changes

2025-01-09 18:35 UTC, jraman567 commented on api/server.go
> +var _ ServerInterface = (*Server)(nil)
I don't think this line is necessary to implement the server interface. Since RatsdChares is defined below, that automatically implements the interface.

So, you can remove this line. Thanks!

2025-01-09 18:36 UTC, jraman567 commented on api/server.go
> +var _ ServerInterface = (*Server)(nil)
@cowbon Thanks for the PR, tom! I've completed the review and requested some changes. If you want to discuss it, I'm glad to setup a meeting. Cheers.

2025-01-10 06:39 UTC, cowbon commented on cmd/main.go
> +		Protocol: "https",
For https Cert and Certkey, is it fine to reuse the one from Veraison/services?

Regarding the code generation, `tools.go` is a pattern to remove `go generate` from the Makefile, see https://www.jvt.me/posts/2022/06/15/go-tools-dependency-management/. IMO the generated code is beyond the scope of the test coverage of ratsd as it should be covered by `oapi-codegen`.

2025-01-10 09:50 UTC, thomas-fossati commented on cmd/main.go
> +		Protocol: "https",
> For https Cert and Certkey, is it fine to reuse the one from Veraison/services?

We can reuse the infrastructure (e.g., the rootCA and scripts) but the end-entity certificate used by ratsd should be made ad-hoc, with a subject/SAN matching the expected hostname.

2025-01-10 12:13 UTC, thomas-fossati commented on cmd/main.go
> +		Protocol: "https",
Hi @jraman567 

> * Add a CI pipeline that runs whenever someone submits a PR

A barebones CI for the Go code has been in place since adf98a3

Until we add e2e tests, that should be enough.

Are you thinking of something different/special?

2025-01-10 12:34 UTC, thomas-fossati commented on api/server.go
> +}
Question: do you want to add all the checks on input conformance (e.g., C-T, nonce format), and content negotiation in a subsequent PR along with the tests?

If so, I am OK with that, but we need to make that a bit more explicit - i.e., with one or more well-scoped tracking issue(s).

2025-01-10 14:51 UTC, jraman567 commented on cmd/main.go
> +		Protocol: "https",
@cowbon See https://github.com/veraison/services/blob/main/deployments/docker/src/certs/gen-certs on how Veraison generates certificates

2025-01-10 14:52 UTC, jraman567 commented on cmd/main.go
> +		Protocol: "https",
@thomas-fossati I think the CI for the Go code you added looks good. Thank you!

2025-01-10 14:59 UTC, thomas-fossati commented on cmd/main.go
> +		Protocol: "https",
On reflection, we probably need to update the go version used by the CI (currently 1.20) to reflect the requirements introduced by this PR.

2025-01-10 15:02 UTC, jraman567 commented on cmd/main.go
> +		Protocol: "https",
@cowbon Concerning tools.go, it's only needed if your go generate comment was like below in api/doc.go
//go:generate oapi-codegen --config=config.yaml ../docs/api/ratsd.yaml

Since you specify the full path of the oapi-codegen repo like below, the tools.go file isn't necessary to first download and build the tool
//go:generate go run github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen --config=config.yaml ../docs/api/ratsd.yaml

Are you seeing any issues with removing the tools directory? I'm in favor of removing it as it doesn't appear to be doing any function presently.

2025-01-10 15:05 UTC, jraman567 commented on cmd/main.go
> +		Protocol: "https",
I don't know if it's best to push `api/api.gen.go` to the repo or if it's better to generate it using `go generate` during the build process.

I prefer to generate it during the build process. Something like
`go generate; go build`

@thomas-fossati Do you have any thoughts?

2025-01-10 15:05 UTC, cowbon commented on cmd/main.go
> +		Protocol: "https",
> On reflection, we probably need to update the go version used by the CI (currently 1.20) to reflect the requirements introduced by this PR.

Since the version bump is only introduced in this PR, I can bring it in as part of the rework

2025-01-10 15:07 UTC, jraman567 commented on cmd/main.go
> +		Protocol: "https",
> On reflection, we probably need to update the go version used by the CI (currently 1.20) to reflect the requirements introduced by this PR.

I agree

2025-01-10 15:24 UTC, thomas-fossati commented on cmd/main.go
> +		Protocol: "https",
> I don't know if it's best to push `api/api.gen.go` to the repo or if it's better to generate it using `go generate` during the build process.
> 
> I prefer to generate it during the build process. Something like `go generate; go build`
> 
> @thomas-fossati Do you have any thoughts?

The risk of regenerating on each build is that, unless we can reference a specific version of the YAML file, the business logic may break if the OpenAPI file changes.
That would add complexity each time we move the YAML, e.g., to add/tweak some functionality...

My two cents:
* Add the generated code to the repo.
* Add an explicit make rule (or script) to regenerate the code when necessary (i.e.,  when the API spec is updated).

2025-01-10 15:33 UTC, jraman567 commented on cmd/main.go
> +		Protocol: "https",
OK, that sounds good to me concerning code generation.

2025-01-13 21:49 UTC, cowbon commented on api/server.go
> +var _ ServerInterface = (*Server)(nil)
The type check is not deemed necessary. I removed it in the latest version of the patchset.

2025-01-13 21:53 UTC, cowbon commented on api/server.go
> +}
@thomas-fossati Should I go ahead to create a Github issue to state that it warrants a format check? I'd want to make clear the format of C-T and nonce to proceed on.

2025-01-14 15:45 UTC, cowbon commented on cmd/main.go
> +		Protocol: "https",
> If the default is https, do you need the default Cert & CertKey for it?

I recently added something similar to `gen_cert` in Veraison for HTTPS, but I also made the default protocol to be `http` instead of `https`. @jraman567 Does that make sense to you?

2025-01-14 15:49 UTC, thomas-fossati commented on api/server.go
> +}
Please, go ahead and create the issue.  The things to check are, at least:
* payload consistency (`Content-Type` header and format of the JSON payload)
* HTTP content negotiation (obey any `Accept` header)

2025-01-14 15:57 UTC, thomas-fossati commented on ratsd.crt
There should be a Makefile target to re-generate the chain.

2025-01-14 15:57 UTC, thomas-fossati commented on cmd/config.yaml
> +  protocol: http
Since we have the certs, I guess this can be https, no?

2025-01-14 15:57 UTC, thomas-fossati commented on gen-certs
> +# Copyright 2024 Contributors to the Veraison project. SPDX-License-Identifier: Apache-2.0
```suggestion
# Copyright 2025 Contributors to the Veraison project.
```

2025-01-14 15:58 UTC, thomas-fossati commented
Thanks for the changes @cowbon!  I have added a couple of new comments inline.

2025-01-15 16:35 UTC, iolivergithub commented
I'm getting the following on this branch

```
ian@Debian:~/ratsd$ make
go generate ./api
go build -o ratsd ./cmd
# github.com/veraison/services/log
../go/pkg/mod/github.com/veraison/services@v0.0.2501/log/hclogger.go:119:9: cannot use &HCLogger{…} (value of type *HCLogger) as hclog.Logger value in return statement: *HCLogger does not implement hclog.Logger (missing method GetLevel)
../go/pkg/mod/github.com/veraison/services@v0.0.2501/log/hclogger.go:140:9: cannot use &HCLogger{…} (value of type *HCLogger) as hclog.Logger value in return statement: *HCLogger does not implement hclog.Logger (missing method GetLevel)
../go/pkg/mod/github.com/veraison/services@v0.0.2501/log/hclogger.go:161:9: cannot use &HCLogger{…} (value of type *HCLogger) as hclog.Logger value in return statement: *HCLogger does not implement hclog.Logger (missing method GetLevel)
make: *** [Makefile:16: build] Error 1
ian@Debian:~/ratsd$ go version
go version go1.23.2 linux/amd64
```

2025-01-15 18:25 UTC, cowbon commented
> I'm getting the following on this branch
> 
> ```
> ian@Debian:~/ratsd$ go version
> go version go1.23.2 linux/amd64
> an@Debian:~/ratsd$ go mod tidy
> go: downloading github.com/sagikazarmark/locafero v0.4.0
> go: downloading github.com/bytedance/sonic v1.11.3
> go: downloading github.com/goccy/go-json v0.10.2
> go: downloading github.com/json-iterator/go v1.1.12
> go: downloading go.uber.org/goleak v1.3.0
> go: downloading github.com/go-test/deep v1.0.8
> go: downloading gopkg.in/check.v1 v1.0.0-20201130134442-10cb98267c6c
> go: downloading golang.org/x/exp v0.0.0-20230905200255-921286631fa9
> go: downloading github.com/frankban/quicktest v1.14.6
> go: downloading github.com/go-playground/assert/v2 v2.2.0
> go: downloading github.com/davecgh/go-spew v1.1.2-0.20180830191138-d8f796af33cc
> go: downloading github.com/pmezard/go-difflib v1.0.1-0.20181226105442-5d4384ee4fb2
> go: downloading github.com/modern-go/reflect2 v1.0.2
> go: downloading github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd
> go: downloading github.com/sourcegraph/conc v0.3.0
> go: downloading github.com/kr/pretty v0.3.1
> go: downloading github.com/kr/text v0.2.0
> go: downloading github.com/rogpeppe/go-internal v1.12.0
> go: downloading github.com/chenzhuoyu/base64x v0.0.0-20230717121745-296ad89f973d
> go: downloading golang.org/x/arch v0.7.0
> go: downloading github.com/twitchyliquid64/golang-asm v0.15.1
> go: downloading github.com/chenzhuoyu/iasm v0.9.0
> go: downloading github.com/klauspost/cpuid/v2 v2.2.7
> ian@Debian:~/ratsd$ make
> go generate ./api
> no required module provides package github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen; to add it:
> 	go get github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen
> api/doc.go:3: running "go": exit status 1
> make: *** [Makefile:12: generate] Error 1
> ian@Debian:~/ratsd$     go get github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen
> go: added github.com/dprotaso/go-yit v0.0.0-20220510233725-9ba8df137936
> go: added github.com/oapi-codegen/oapi-codegen/v2 v2.4.1
> go: added github.com/speakeasy-api/openapi-overlay v0.9.0
> go: added github.com/vmware-labs/yaml-jsonpath v0.3.2
> ian@Debian:~/ratsd$ make
> go generate ./api
> go build -o ratsd ./cmd
> # github.com/veraison/services/log
> ../go/pkg/mod/github.com/veraison/services@v0.0.2501/log/hclogger.go:119:9: cannot use &HCLogger{…} (value of type *HCLogger) as hclog.Logger value in return statement: *HCLogger does not implement hclog.Logger (missing method GetLevel)
> ../go/pkg/mod/github.com/veraison/services@v0.0.2501/log/hclogger.go:140:9: cannot use &HCLogger{…} (value of type *HCLogger) as hclog.Logger value in return statement: *HCLogger does not implement hclog.Logger (missing method GetLevel)
> ../go/pkg/mod/github.com/veraison/services@v0.0.2501/log/hclogger.go:161:9: cannot use &HCLogger{…} (value of type *HCLogger) as hclog.Logger value in return statement: *HCLogger does not implement hclog.Logger (missing method GetLevel)
> make: *** [Makefile:16: build] Error 1
> ```

Thanks Ian,
I've regenerate `go.sum` and `go.mod` and now there should be no build issue.

2025-01-15 18:25 UTC, closed without merging

2025-01-15 18:33 UTC, cowbon commented on cmd/config.yaml
> +  protocol: http
Yes, I've updated it to `https` in the patch that brings in the required certificates.

2025-01-15 18:33 UTC, cowbon commented on gen-certs
> +# Copyright 2024 Contributors to the Veraison project. SPDX-License-Identifier: Apache-2.0
Thanks for pointing this out.

2025-01-15 19:21 UTC, cowbon commented on ratsd.crt
`gen-certs` and `clean-certs` are now added to the Makefile.

2025-01-15 19:23 UTC, cowbon commented
I accidentally closed the PR. Recreate another one.

2025-01-15 19:25 UTC, cowbon commented
Recreate the PR with the following fixes:
 1. HTTPS certificates 
 2. HTTP request conformance check
 3. Makefile related issues
 4. go.mod updates